image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


#uusi
include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: test
  variables:
    CODE_QUALITY_IMAGE: "registry.example.com/codequality-fork:latest"
#uusi

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install requests
  - pip3 install python-dotenv
  - pip3 install pygame

test:
  script:
      - echo "ei testejä"
